artifacts:
  files:
  - .ebextensions
  - config.ru
  - Gemfile
  - README.md
  - Rakefile
  - app/**/*
  - config/**/*
  - db/**/*
  - log/**/*
  - public/**/*
  - vendor/**/*
  type: zip
eb_codebuild_settings:
  CodeBuildServiceRole: aws-codestar-service-role
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/eb-ruby-2.3-amazonlinux-64:2.3.2
  Timeout: null
phases:
  install:
    commands:
    - pip install --upgrade awscli
    - bundle install
  pre_build:
    commands:
    - export SECRET_KEY_BASE=$(rake secret)
    - rspec
version: 0.2
